version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: uneaty-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:4000/api
    command: npm start
    depends_on:
      - backend
    networks:
      - uneaty-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uneaty-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/uneaty
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRE=30d
    command: npm run dev
    depends_on:
      - mongo
    networks:
      - uneaty-network

  mongo:
    image: mongo:latest
    container_name: uneaty-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - uneaty-network

networks:
  uneaty-network:
    driver: bridge

volumes:
  mongo-data: