apiVersion: apps/v1
kind: Deployment
metadata:
  name: uneaty-backend
  namespace: uneaty
  labels:
    app: uneaty-backend
    environment: ${environment}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uneaty-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: uneaty-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "4000"
    spec:
      containers:
      - name: uneaty-backend
        image: ${DOCKER_USERNAME}/uneaty-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: uneaty-secrets
              key: mongo-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: uneaty-secrets
              key: jwt-secret
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: uneaty-secrets
              key: redis-host
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uneaty-frontend
  namespace: uneaty
  labels:
    app: uneaty-frontend
    environment: ${environment}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uneaty-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: uneaty-frontend
    spec:
      containers:
      - name: uneaty-frontend
        image: ${DOCKER_USERNAME}/uneaty-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "/api"
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10