apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uneaty-ingress
  namespace: uneaty
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: uneaty.example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: uneaty-backend
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uneaty-frontend
            port:
              number: 80